# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('start_date', models.DateField(db_index=True, null=True)),
                ('due_date', models.DateField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('start_date', models.DateField(db_index=True, null=True)),
                ('due_date', models.DateField(db_index=True, null=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Release')),
            ],
        ),
        migrations.CreateModel(
            name='StoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('feature', models.TextField()),
                ('benefit', models.TextField()),
                ('points', models.IntegerField()),
                ('due_date', models.DateField(db_index=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('owners', models.ManyToManyField(blank=True, db_index=True, to=settings.AUTH_USER_MODEL)),
                ('required', models.ManyToManyField(blank=True, db_index=True, related_name='_userstory_required_+', to='main.UserStory')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Role')),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sprint')),
                ('tags', models.ManyToManyField(blank=True, db_index=True, to='main.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='storylog',
            name='story',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.UserStory'),
        ),
    ]
