# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='owner',
        ),
        migrations.AddField(
            model_name='release',
            name='due_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='start_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='created_date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstory',
            name='last_updated_date',
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='owners',
            field=models.ManyToManyField(db_index=True, to='main.User'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='required',
            field=models.ManyToManyField(db_index=True, related_name='_userstory_required_+', to='main.UserStory'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='release',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='due_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='due_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tags',
            field=models.ManyToManyField(db_index=True, to='main.Tag'),
        ),
        migrations.AddField(
            model_name='storylog',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='storylog',
            name='story',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.UserStory'),
        ),
    ]
