# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171104_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sprint'),
        ),
    ]
