# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171104_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userstory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
