# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171104_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
